shell = "zsh"
working_directory = "/home/memo"

[font]
size = 12.5

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.offset]
x = -1

[window.padding]
x = 6
y = 7
